Для предварительной оценки
htmlacademy-htmlcss/845199-nerds-31 pull request #10
Opened 2021-07-10 20:53 UTC by dopamine-s

2021-07-10 22:00 UTC, wrgraff requested changes

2021-07-10 22:00 UTC, wrgraff commented on js/modal.js
> +      const textarea = popup.querySelector("textarea");
Что-то не так пошло с форматированием этого файла

2021-07-10 22:00 UTC, wrgraff commented on js/modal.js
> +      const textarea = popup.querySelector("textarea");
Надо поправить, а то это базовый критерий

2021-07-10 22:00 UTC, wrgraff commented on catalog.html
> +          <!--<img class="contacts-map" src="img/adress-map-background.png" width="1440" height="416" alt="Карта проезда">-->
Комментарий лучше убрать, опять же можно по оформлению кода не пройти из-за него

2021-07-10 22:19 UTC, dopamine-s commented on js/modal.js
> +      const textarea = popup.querySelector("textarea");
Поправил

2021-07-10 22:19 UTC, dopamine-s commented on catalog.html
> +          <!--<img class="contacts-map" src="img/adress-map-background.png" width="1440" height="416" alt="Карта проезда">-->
Убрал

2021-07-11 07:59 UTC, wrgraff approved these changes

2021-07-11 08:00 UTC, merged