Добавляет разметку первой страницы
htmlacademy-htmlcss/845199-nerds-31 pull request #2
Opened 2021-05-23 14:54 UTC by dopamine-s

2021-05-23 20:24 UTC, wrgraff requested changes
Хорошая работа, правок не очень много

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +          <li><a href="#">студия</a></li>
Лучше тег внутри тега писать на новой строчке:
```html
<li>
  <a href="#">студия</a>
</li>
```

Желательно еще писать текст нормально, как обычно, с большой буквы и строчными: "Студия"

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +            <p>Долго, дорого,<br />скрупулезно.</p>
Давай договоримся пока не использовать `<br />`.
Дело в том, что форматированный текст вести себя будет иначе, а нам на этапе сеток нужно будет убедиться, что он подстраивается под сетку вне зависимости от форматирования.
Мы потом сможем поставить переносы, если это будет нужно.

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +        <a class="our-features-link" href="#">Узнать больше</a>
Эта ссылка есть в каждом слайде, а не снаружи.
Они даже могут вести на разные страницы

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +          <li><button type="button"></button></li>
Хорошо бы в кнопках написать текст

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +        <h2>Наши уникальные особенности</h2>
Получается, что заголовок второго уровня идет перед заголовком первого.
Это неправильно, заголовки как дерево: меньшие вырастают только из больших, а h1 — это ствол

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +            <p>веб-сайты</p>
Нельзя ли сказать, что по структуре это заголовок?

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +      <section class="c">
Что это за класс такой?
Команда А, Мистер Т, Секция С?.. Такая логика? )

Назови нормально, раз уж начал

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +            /></a>
Что за странные переносы тегов?
Не надо так, надо нормально

2021-05-23 20:24 UTC, wrgraff commented on index.html
> +          <a href="#">напишите нам</a>
Я бы не стал это в параграфе одном держать с текстом адреса

2021-05-24 07:09 UTC, dopamine-s commented on index.html
> +    <header class="main-header">
Некоторые классы стояли в шаблоне, который я получил. Поэтому, я посчитал, что это нормально. И некоторые классы уже добавил сам.

2021-05-24 07:11 UTC, dopamine-s commented on index.html
> +<html lang="en">
Да, не очень. Язык по умолчанию был выставлен в шаблоне, который я скачал. В демке, в которую я подглядывал (Барбершоп) язык тоже ru. Вводит в заблуждение, знаете ли)

2021-05-24 07:14 UTC, dopamine-s commented on index.html
> +          <li><a href="#">студия</a></li>
С текстом могу сделать. С тегами - сложней. У меня стоит Prettier, он автоматически все причёсывает. Боюсь, что тонко его настроить я смогу только с указаниями. Когда я настраивал его в первый раз, обращался за помощью тоже.

2021-05-24 07:16 UTC, dopamine-s commented on index.html
> +            <p>Долго, дорого,<br />скрупулезно.</p>
Я предвидел этот комментарий, убрал эти тэги по максимуму, оставил только там, где, как мне показалось, уже правки вносится не будут. Ну то есть текст уже завершен, и не будет ничего меняться вообще. ОК, уберу совсем

2021-05-24 07:21 UTC, dopamine-s commented on index.html
> +    <header class="main-header">
Думаю, я пока оставлю  как есть. Времени уже не очень много, я еще вторую страницу не доверстал. Исправлю только ошибки.

2021-05-24 07:24 UTC, dopamine-s commented on index.html
> +          <li><a href="#">студия</a></li>
Проверил. Это я могу сделать, это не поправляет. ОК.

2021-05-24 07:26 UTC, dopamine-s commented on index.html
> +            <p>Долго, дорого,<br />скрупулезно.</p>
В оформлении всяких окошек для ввода тоже этот тег не использовать?

2021-05-24 07:28 UTC, dopamine-s commented on index.html
> +            <p>Долго, дорого,<br />скрупулезно.</p>
Пока оставил, убрал только из текста.

2021-05-24 07:33 UTC, dopamine-s commented on index.html
> +          <li><a href="#">студия</a></li>
Кусок с placeholder ами выравнивает неединообразно. Это зависит от их длины, я тут уже я не могу ничего поделать.

2021-05-24 13:12 UTC, wrgraff commented on index.html
> +<html lang="en">
Ну так ты и не исправил язык.
Должен быть `ru`. У тебя страница на русском языке. Если ты ставишь `en`, то создаешь по сути вместо страницы с текстом страницу с набором непонятных букв, как я описал.

2021-05-24 13:16 UTC, wrgraff commented on index.html
> +          <li><a href="#">студия</a></li>
Можно удалить prettier и для начала приучиться писать код аккуратно руками.
prettier есть не всегда и не всегда его можно настроить под требования проекта (и на втором уровне будут как раз гораздо строже требования).
Неплохо бы приучиться обходиться одним editorconfig'ом пока что.
И вообще, зачем пользоваться тем, что не можешь пока что сам настроить?

2021-05-24 13:17 UTC, wrgraff commented on index.html
> +            <p>Долго, дорого,<br />скрупулезно.</p>
Этот тег только для форматирования текста.
Для расположения элементов его использовать нельзя, так как для этого у нас будет целый CSS

2021-05-24 13:39 UTC, wrgraff requested changes
Так, давай не ленись, а поправляй все.
Мне сказали, что ты потянешь, и я пока не вижу причин, почему нет.

2021-05-24 13:39 UTC, wrgraff commented on index.html
> +            <button type="button"></button>
Текст в кнопки не поставил.
Разве это сложная задача? Даже если не обязательная. Сомневаюсь, что ты тут сэкономил много времени на пропуске этого комментария.

Ты пока что достаточно хорошо справляешься, чтобы править всё, а не только необходимое.

2021-05-24 13:39 UTC, wrgraff commented on index.html
> +        <h2>Наши уникальные особенности</h2>
Тоже не поправил, при чем важный же момент.
Структуру документа потом запаришься править, если не сделать это сейчас.

2021-05-24 13:39 UTC, wrgraff commented on index.html
> +            <p>Веб-сайты</p>
Эти подписи будут в структуре документа смотреться весьма уместно.
У тебя список из 3 пунктов. Каждый пункт — осмысленный. Каждый пункт может иметь заголовок. Более того, не только в разметке фантомные заголовки здесь, но и в самом макете они явно выделяются:
<img width="335" alt="изображение" src="https://user-images.githubusercontent.com/37917037/119354321-a004d480-bcac-11eb-978d-7529251a94cf.png">

А ты их игнорируешь. Плохо

2021-05-24 13:39 UTC, wrgraff commented on index.html
> +              />
Странные переносы остались на месте.
Я так не приму работу. Или с Приттером разбирайся, или пиши без него, если пока не можешь с ним управиться.
Но код должен быть оформлен как положено. А не "как получилось".

2021-05-24 13:39 UTC, wrgraff commented on index.html
> +          <a href="#">напишите нам</a>
Обязательность — это чтобы понимать какие правки не помешают принять задание.
Но на мое удовлетворение от работы влияет исправление всех поправок )

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +            <a href="#">Магазин</a>
Почему тут решетка в адресе?

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +      <h1>Магазин готовых шаблонов</h1>
Вот у тебя на главной порядок заголовков неправильный.
Потому что ты поставил заголовок первого уровня в `<main>`. Все, что там требуется — перебросить его в хэдер, чтобы он перед слайдером был.
Я думал, ты не хочешь его в хэдер ставить. Но дело не в этом. А в чем тогда?

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +            <label for="price-range-start"></label>
Пустой лейбл не считается

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +            <label for="price-range-end-input">До</label>
Почему порядок странный такой?

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +              <p>Sedona</p>
По ТЗ у нас ссылкой должна быть надпись "Sedona", а не картинка

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +              <p>Sedona</p>
В таких списках хорошо работают заголовки

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +            <a href="product.html">
У тебя разве есть в макете страница `product.html`?
Зачем ты ставишь ссылку на страницу, которая ничего не покажет, кроме ошибки?

2021-05-24 13:39 UTC, wrgraff commented on catalog.html
> +          </li>
Во всех шаблонах есть текст как и в Седоне.
Все это есть в макете в скрытых слоях. Разметить надо все.

2021-05-24 14:08 UTC, dopamine-s commented on index.html
> +        <h2>Наши уникальные особенности</h2>
Изменил на параграф.

2021-05-24 14:11 UTC, dopamine-s commented on index.html
> +            <p>веб-сайты</p>
Не совсем понял, что следует сделать. Секция самостоятельная. "Услуги" подходит на ее заголовок. Что не так?

2021-05-24 14:13 UTC, dopamine-s commented on index.html
> +      <section class="c">
Исправлено.

2021-05-24 14:33 UTC, dopamine-s commented on index.html
> +            <button type="button"></button>
Я даже не подумал, что для кнопок нужен текст. Что-то вроде Слайд 1, 2, 3?

2021-05-24 14:34 UTC, dopamine-s commented on index.html
> +            <p>Веб-сайты</p>
Я не игнорирую. Мне сложно понять, где уместно ставить заголовок, а где будет просто выделение текста

2021-05-24 14:54 UTC, dopamine-s commented on catalog.html
> +      <h1>Магазин готовых шаблонов</h1>
Да, дело в этом. Я просто не разобрался с тем, как мы работаем. Мне нужно было проверять ответы тут, а я ждал ответа на форму в обучении. Поэтому некоторые ошибки я просто не исправил, потому что не видел, что на них уже есть обратная связь. Я сейчас поправлю

2021-05-24 14:57 UTC, dopamine-s commented on catalog.html
> +            <a href="#">Магазин</a>
Исправил. Мне казалось, что для той же страницы не нужно задавать активную ссылку. Ну, если ты уже и так на этой странице. Например, в Магазине.

2021-05-24 14:57 UTC, dopamine-s commented on index.html
> +              />
А к кому обратиться по работе Приттера? Вроде его рекомендовали поставить. Предполагается. что он правильно оформляет текст. Получается. рекомендацию нужно было проигнорировать? Я не знаю, как его правильно настроить. Могу только отключить.

2021-05-24 15:02 UTC, dopamine-s commented on index.html
> +        <h2>Наши уникальные особенности</h2>
Перенес заголовок первого уровня. Сделал секцию назад.

2021-05-24 15:03 UTC, dopamine-s commented on index.html
> +            /></a>
Я стараюсь понять, как работает плагин. Но для него это нормальная логика работы. Нужно пробовать что-то еще.

2021-05-24 15:06 UTC, dopamine-s commented on index.html
> +          <a href="#">напишите нам</a>
Обособил текст и ссылки. Обернул отдельно в p. Блок обернул в див

2021-05-24 15:07 UTC, dopamine-s commented on index.html
> +            <button type="button"></button>
Поместил в кнопки текст "Особенность 1", ...2,...3.

2021-05-24 15:08 UTC, dopamine-s commented on index.html
> +            <p>Веб-сайты</p>
Сделал заголовками третьего уровня

2021-05-24 15:09 UTC, dopamine-s commented on index.html
> +              />
Перед финальным сохранением буду отключать плагин. Хотя это очень странно

2021-05-24 15:12 UTC, dopamine-s commented on catalog.html
> +            <label for="price-range-start"></label>
Лэйбл потом скрывается? Хорошо, понял

2021-05-24 15:14 UTC, dopamine-s commented on catalog.html
> +            <label for="price-range-start"></label>
Добавил

2021-05-24 15:14 UTC, dopamine-s commented on catalog.html
> +            <label for="price-range-end-input">До</label>
Исправил

2021-05-24 15:15 UTC, dopamine-s commented on catalog.html
> +              <p>Sedona</p>
Верно. Исправил

2021-05-24 15:25 UTC, dopamine-s commented on catalog.html
> +              <p>Sedona</p>
Согласен. Исправил

2021-05-24 15:25 UTC, dopamine-s commented on catalog.html
> +            <a href="product.html">
Исправил

2021-05-24 15:25 UTC, dopamine-s commented on catalog.html
> +          </li>
Исправил

2021-05-24 21:51 UTC, wrgraff commented on catalog.html
> +              placeholder="15 000"
Это кстати я недосмотрел (хотя, это более важно будет позже).
Тут значение такое должно быть, не просто плейсхолдер

2021-05-24 21:51 UTC, wrgraff commented on index.html
> +            <button type="button">Особенность 1</button>
Особенность... Ну ладно )

2021-05-24 21:51 UTC, wrgraff commented on index.html
> +            <p>Веб-сайты</p>
Правильно сделал )

2021-05-24 21:54 UTC, wrgraff commented on index.html
> +              />
Я предположу, что если ты будешь сразу сносить картинку на новую строку, то он так делать не будет.
Потому что здесь он из-за слишком длинной строки, в которой и ссылка, и картинка, делает то, что он всегда делает в таких ситуациях: сносит аргументы по строкам.
А тег картинки при этом не сносит.

2021-05-24 21:57 UTC, wrgraff commented on index.html
> +              />
Главное, чтобы он хотя бы ссылку не рвал на части.
А вообще, я рекомендую пока просто попользоваться эдиторконфигом: https://youtu.be/wWbDC1C7JEE
Потом уже когда больше будешь на JS писать, логичнее в Prittier включаться

2021-05-24 21:58 UTC, wrgraff commented on catalog.html
> +            <a href="#">Магазин</a>
Тогда ты можешь вообще не задавать атрибут `href`

2021-05-24 21:59 UTC, wrgraff commented on catalog.html
> +      <h1>Магазин готовых шаблонов</h1>
Если не хочется ставить его в хэдер, можно тогда слайды сделать внутри блока `<main>`

2021-05-24 21:59 UTC, wrgraff commented on catalog.html
> +            <label for="price-range-start"></label>
Да, скрывать можно, как и загшоловки невидимые

2021-05-24 22:00 UTC, wrgraff commented on catalog.html
> +              <p>Sedona</p>
Сам знаю что верно 😀

2021-05-24 22:02 UTC, wrgraff approved these changes
Что-то там несущественное я еще отметил, но так как на правильность это не влияет, то принимаю.
А исправить можешь в следующем задании

2021-05-24 22:02 UTC, merged

2021-05-24 22:29 UTC, dopamine-s commented on index.html
> +              />
Установил этот плагин через менеджер плагинов. Попробую. Спасибо за инфу.