Базово стилизует главную страницу
htmlacademy-htmlcss/845199-nerds-31 pull request #4
Opened 2021-06-01 19:31 UTC by dopamine-s

2021-06-02 19:07 UTC, wrgraff requested changes

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  box-shadow: inset 0px 3px 0px rgba(0, 1, 1, 0.1);
Как минимум эти 2 параметра можно описать для всех `services-link`, а не для каждого.
Более того, они вообще едины для всех кнопок.

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  background-image: url(../img/nerds-about-img1.png);
Адреса выше в кавычках написаны.
Придерживайся единого стиля

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  text-align: left;
Зачем ты ставишь все время выравнивание по левому краю?
Этот код ничего не делает же. И так много раз.

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  vertical-align: text-top;
Откуда ты вытащил то это значение )

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  min-height: 416px;
Базовую стилизацию делаем.
Зачем нам `min-height`?

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +.feedback-form input[type="email"],
А если других типов инпуты будут?

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +  font: inherit;
Зачем переписывать инпутам шрифт, если он выше уже переписан?
При чем, там для 2-х типов он переписан, а тут для любого инпута в фокусе. То есть, на инпуте с типом `tel`, например, у нас шрифт скаканет

2021-06-02 19:07 UTC, wrgraff commented on css/style.css
> +.feedback-form .invalid-input:invalid {
Достаточно написать стили для класса `.invalid-input` без всей остальной мишуры.
Его затем можно будет ставить через js

2021-06-02 22:56 UTC, dopamine-s commented on css/style.css
> +.main-header {
После тегов идет пустая строка, дальше классы. Поправил.

2021-06-02 23:20 UTC, dopamine-s commented on index.html
> +        <div class="user-navigation">
Ну я подумал, что в дальнейшем может понадобится добавить авторизацию. Для этого подошел бы этот div. Чтобы стилизовать корзину вместе со ссылкой на личный кабинет или что там еще.

2021-06-02 23:20 UTC, dopamine-s commented on index.html
> +        <a class="basket-link" href="#">Корзина</a>
Переименовал

2021-06-02 23:28 UTC, dopamine-s commented on index.html
> +            <a class="functional-link slider-link" href="#">Узнать больше</a>
Поправил на our-features-link

2021-06-03 20:57 UTC, dopamine-s commented on index.html
> +          <li class="our-features-button">
Исправил

2021-06-03 21:00 UTC, dopamine-s commented on index.html
> +            <a class="functional-link services-link" href="#">заказать</a>
Исправил

2021-06-03 21:03 UTC, dopamine-s commented on index.html
> +              <p class="about-location">Мы — маленькая, но гордая дизайн-студия из Краснодара.</p>
Исправил на about-slogan.

2021-06-03 21:08 UTC, dopamine-s commented on index.html
> +              <p class="about-principles">
А от чего отталкиваться? От смысла - неверно. От формы - неверно. 

Исправил на:  about-team

2021-06-03 21:12 UTC, dopamine-s commented on index.html
> +          <p><a class="functional-link" href="#">напишите нам</a></p>
Для единообразия в названиях классов. Все, что фактически стилизует ссылки, как бы не выглядело, называется link. У нас же еще будут классы с link в названии для дополнительной стилизации. И будут реальные button, являющиеся кнопками. Разве так не логично, чтобы не запутаться? Я оставлю так, если это возможно.

2021-06-03 21:15 UTC, dopamine-s commented on index.html
> +          <input class="invalid-input" id="name-field" type="text" placeholder="Имя Фамилия" required/>
Название выбрано некорректно, как я понимаю. Но класс нужен для проверки валидности. Отталкиваться нужно, вероятно, именно от валидности.  Мне кажется, если назвать input-validity-check , то это будет выглядеть правильней?

2021-06-03 21:15 UTC, dopamine-s commented on index.html
> +          <input class="invalid-input" id="name-field" type="text" placeholder="Имя Фамилия" required/>
Дал класс input-validity-check

2021-06-03 21:54 UTC, dopamine-s commented on css/style.css
> + --basic-dark: #283136;
Видел. Я думал, это рекомендация. А это - НАСТОЯТЕЛЬНАЯ рекомендация, да? 
Хорошо, понял. Исправил

2021-06-03 22:10 UTC, dopamine-s commented on css/style.css
> + .social-links {
Хорошо, понял. Разнес классы по документу.

2021-06-03 22:15 UTC, dopamine-s commented on css/style.css
> +.user-navigation a{
Проще. А вдруг мы захотим выделить блоки ссылок? Добавим ссылку для логина, подсветим ее с корзиной отдельным цветом? Тут уже заготовка. 
Впрочем, всегда можно исправить. Просто непонятна логика. То - думай на будущее. То - делай как нужно по макету и все. 
У меня, конечно, нет опыта. 
Задал ссылки для main-navigation в целом. Как скажете, босс.

2021-06-03 22:33 UTC, dopamine-s commented on css/style.css
> +.navigation-link a:hover,
Согласен, если вдуматься. Но если усложнять, не будет еще хуже?
Поменял на "Пункт"
user-navigation-item

2021-06-03 22:34 UTC, dopamine-s commented on css/style.css
> +  text-align: left;
Насмотрелся не туда, когда смотрел примеры по учебе.
 Убрал.

2021-06-03 22:34 UTC, dopamine-s commented on css/style.css
> +  text-align: left;
Погорячился) Убрал.

2021-06-03 22:36 UTC, dopamine-s commented on css/style.css
> +  font: inherit;
Согласен. Ориентировался на пример из учебного проекта. Там сделано так. 
Изменил.

2021-06-03 22:49 UTC, dopamine-s commented on css/style.css
> +  box-shadow: inset 0px 3px 0px rgba(0, 1, 1, 0.1);
Сделал

2021-06-04 00:39 UTC, dopamine-s commented on css/style.css
> +}
Мне кажется, эти картинки не несут никакой конкретной нагрузки и взаимозаменяемы. Иначе мы бы не вставляли их фоном. 
Впрочем, можно и прикрепить их к конкретному тексту. 
Прикрепил.

2021-06-04 00:56 UTC, dopamine-s commented on css/style.css
> +}
Закрепил порядок

2021-06-04 00:58 UTC, dopamine-s commented on css/style.css
> +}
Убрал порядковые номера. Всё по классам.

2021-06-04 01:10 UTC, dopamine-s commented on css/style.css
> +  box-shadow: inset 0px 3px 0px rgba(0, 1, 1, 0.1);
Описал для всех services-link.
 Если сделать прямо вот для всех кнопок, это не будет слишком глобально? Есть ли необходимость менять глобально? Возможно, понадобится индивидуально кастомизировать, будет лишняя работа, как со списками, которым я глобально отключил маркеры одним списком, а потом исправлял.

2021-06-04 01:12 UTC, dopamine-s commented on css/style.css
> +  background-image: url(../img/nerds-about-img1.png);
Исправил

2021-06-04 01:14 UTC, dopamine-s commented on css/style.css
> +  text-align: left;
Исправляю

2021-06-04 01:15 UTC, dopamine-s commented on css/style.css
> +  vertical-align: text-top;
Нагуглил) Уберу, потом выровняю.

2021-06-04 01:16 UTC, dopamine-s commented on css/style.css
> +  min-height: 416px;
Убрал

2021-06-04 01:19 UTC, dopamine-s commented on css/style.css
> +.feedback-form input[type="email"],
Отредактировал.

2021-06-04 01:20 UTC, dopamine-s commented on css/style.css
> +  font: inherit;
Отредактировал. Выше убраны типы инпута. Тут убрана строка вообще.

2021-06-04 01:23 UTC, dopamine-s commented on css/style.css
> +.feedback-form .invalid-input:invalid {
Это же не ошибка? Оставляю пока с мишурой, чтобы работало. При необходимости легко изменю.

2021-06-04 21:49 UTC, wrgraff commented on index.html
> +        <div class="user-navigation">
Откуда такой вывод?
Сейчас на сайте никакой авторизации нет и даже нигде нет на нее ни малейшего намека. Нет никаких входов, регистраций и прочего.
Зачем придумывать функцию, которой не существует?
А даже если ее и внедрят, то кто сказал, что именно сюда? Мало ли где ее дизайнер разместит.

2021-06-04 21:53 UTC, wrgraff commented on index.html
> +              <p class="about-principles">
От сути: текст / описание / детали / подробности.
Это просто текст внутри блока about. Вот и все.

2021-06-04 22:00 UTC, wrgraff commented on index.html
> +          <p><a class="functional-link" href="#">напишите нам</a></p>
Единообразие в чем заключается?
Некоторые ссылки (которые похожи на кнопки) называются `functional-link`, некоторые кнопки (которые похожи на кнопки) тоже называются `functional-link`.

И то и другое внешне похоже на кнопку: прямоугольное и красное. А называется "функциональная ссылка". При этом ссылками являются не все эти элементы, некоторые из них по сути кнопки.

Получается, единообразие что ли в том, что все теги `<a>` в классе должны иметь слово "link"?
Что это дает?

2021-06-04 22:09 UTC, wrgraff commented on css/style.css
> + --basic-dark: #283136;
В макете Нердса 10+ серых цветов.
Тут пока 6. А логика с появлением `--basic-dark` который темно-серый уже хромает, потому что есть `--basic-dark-gray` и `--basic-darker-gray`. Он тоже серый, но без слова "серый".
Если бы логика не хромала, не обратил бы внимания

2021-06-04 22:11 UTC, wrgraff commented on css/style.css
> +.main-header {
Пустые строки обычно идут между правилами вообще. А не между тегами и классами

2021-06-04 22:17 UTC, wrgraff commented on css/style.css
> +.user-navigation a{
А если не добавим?
А если добавим, но они все равно черные будут?

Какая-то странная угадайка.
Одно дело, если у нас три слайда, заложиться на то, что будет 4-й. Другое дело — придумать, что мы добавим еще что-то, да еще и цвета начнем менять. Это странно

2021-06-04 22:31 UTC, wrgraff commented on css/style.css
> + --basic-white-100:#ffffff;
Ну только у белого и черного обычно нет градаций оттенков. Они или белый или черный.

2021-06-04 22:33 UTC, merged

2021-06-05 02:16 UTC, dopamine-s commented on index.html
> +          <p><a class="functional-link" href="#">напишите нам</a></p>
Вообще, если разобраться, то да. Я как следует подумал. Поменяю по всему документу. На второй странице используется для стилизации кнопки фильтра. Тогда почему бы действительно не поменять просто на кнопку.