Стилизует каталог
htmlacademy-htmlcss/845199-nerds-31 pull request #5
Opened 2021-06-05 23:02 UTC by dopamine-s

2021-06-07 23:32 UTC, wrgraff requested changes

2021-06-07 23:32 UTC, wrgraff commented on catalog.html
> +          <fieldset class="features-filter">
Вот вопрос на засыпку:
А если нам надо добавить еще один блок полей с чекбоксами? Например, со списком страниц, которые могут быть в шаблоне:
![изображение](https://user-images.githubusercontent.com/37917037/121097936-819aef00-c7fd-11eb-9ed7-1a1de8daa35b.png)
Ты создашь для этого нового блока класс `pages-filter`?

Сайт это все-таки интерфейс. Не привязывайся к смыслу контента, бери его суть. Ведь вне зависимости от того, что за список чекбоксов будет в группе полей, внешний вид никак не изменится.
Ты привязался к смыслу, и получается такая схема оформления:
- Фильтр особенностей
  - Заголовок
  - Список фильтра особенностей

А нужно привязываться к сути элементов, исходить из их функций. Чем астрактнее (но все же точно), тем лучше. Например:
- Группа полей фильтра
  - Заголовок группы полей
  - Список группы полей
    - Элемент группы полей
    - Элемент группы полей
    - Элемент группы полей
    
И так ты можешь поместить туда любой смысл.

2021-06-07 23:32 UTC, wrgraff commented on catalog.html
> +          <p class="sort-container-title">Сортировать</p>
Вообще, надо сказать, что обертка `sort-container` тут не особо нужна.
Да и связка заголовка "Сортировка" и текста "Сортировать" несколько странная. Одно и то же 2 раза, можно же просто сделать "Сортировать" заголовком.

2021-06-07 23:32 UTC, wrgraff commented on catalog.html
> +            <div class="template-item-info">
В чем смысл оборачивания всей карточки? Элемент списка и сам по себе обертка.
Даже если не вдаваться в разметку по дизайну, а просто на код смотреть, закрадываются подозрения:
тут или обертка лишняя, или она не там, где надо.

_А так как я знаю что за дизайн у нас, то могу сказать точно, что тут одно из двух_

2021-06-07 23:32 UTC, wrgraff commented on catalog.html
> +<footer class="main-footer">
Тег уехал

2021-06-07 23:32 UTC, wrgraff commented on css/style.css
> +}
А что, `.main-title` — это каталог?
Похоже больше на то, что это стандартный заголовок для внутренней страницы. И по сути и по названию класса.

2021-06-07 23:32 UTC, wrgraff commented on css/style.css
> +}
Слишком много стилизации через вложенность.
Эти инпуты с лейблами в виде чекбоксов и радио-баттонов представляют собой вполне себе самостоятельный элемент интерфейса.

Они могут встречаться не только в фильтре.
Я даже могу конкретный пример дать. Этому дизайну уже несколько лет, и с тех пор, как его нарисовали, приняли закон о защите прав пользователя. На данный момент первое же, что тебя попросят сделать после верстки такого дизайна — добавить отдельный чекбокс в форму обратной связи (про согласие на обработку данных).

Чекбокс — вполне самостоятельный элемент, который может использоваться сам по себе.

2021-06-07 23:32 UTC, wrgraff commented on css/style.css
> +/*Стилизация каталога завершается. Дальше общая для всех страниц*/
Зачем такой комментарий длинный?
Потом, я бы не делил на твоем месте код на каталог / общие страницы / главная, и так далее.
Все несколько более дробно. Они и те же элементы сайта могут использоваться где угодно.

Например, пагинация может использоваться на странице клиентов, если их там довольно много.
Про чекбоксы писал выше.
Про `main-title` тоже.
Можно придумывать и дальше: некоторые популярные шаблоны могут оказаться на странице "студия".
Инпуты, радио-кнопки и прочие элементы формы с огромной вероятностью окажутся в корзине в оформлении заказа.

В настоящем сайте еще больше таких примеров. Страницы собираются из элементов, модулей и секций.

2021-06-08 01:01 UTC, dopamine-s commented on index.html
> +            <a class="functional-button our-features-link" href="#">Узнать больше</a>
Исправил

2021-06-08 01:20 UTC, dopamine-s commented on catalog.html
> +<footer class="main-footer">
Я поправил

2021-06-08 01:24 UTC, dopamine-s commented on css/style.css
> +}
В том смысле, что main должно относиться только к главной странице? А почему не может быть главного заголовка для второй страницы? 
Ну, если так точней, то. 
catalog-title

2021-06-08 01:29 UTC, dopamine-s commented on css/style.css
> +}
Или назвать просто: title?

2021-06-08 01:31 UTC, dopamine-s commented on css/style.css
> +}
Оставил title

2021-06-08 01:37 UTC, wrgraff commented on css/style.css
> +}
Вообще не о том речь.
Комментарий про то, что этот блок стилей не стоит относить к стилям страницы каталога.
Скорее к общим стилям, как хэдер и футер, так как этот заголовок может оказаться на любой странице

2021-06-08 02:08 UTC, dopamine-s commented on css/style.css
> +}
А. Вот теперь понял.

2021-06-08 23:41 UTC, dopamine-s commented on catalog.html
> +            <div class="template-item-info">
Исправил

2021-06-08 23:42 UTC, dopamine-s commented on css/style.css
> +/*Стилизация каталога завершается. Дальше общая для всех страниц*/
Буду иметь в виду. Комментарий убрал, в дальнейшем не буду разносить блоками.

2021-06-09 00:10 UTC, dopamine-s commented on catalog.html
> +          <fieldset class="features-filter">
Поменял названия классов на универсальные, которые отталкиваются не от смысла, а от функциональности.

2021-06-09 00:11 UTC, dopamine-s commented on css/style.css
> +}
Поменял названия классов на универсальные, которые отталкиваются не от смысла, а от функциональности.

2021-06-09 00:56 UTC, wrgraff commented on css/style.css
> +/*Стилизация каталога завершается. Дальше общая для всех страниц*/
В дальнейшем придет БЭМ и препроцессор и станет все намного системнее )
А тут мы пока так, в песочнице балуемся. Но принцип такой, да.

2021-06-09 00:59 UTC, wrgraff commented on catalog.html
> +            <div class="template-item-info">
На самом деле, тебе придется сделать обертку, просто не для всего содержания, а для того, что появляется при наведении.
То есть, обертка все равно будет. Но она включит все, кроме картинки. В этом была вся соль

2021-06-09 01:01 UTC, wrgraff commented on css/style.css
> +}
Тут еще момент в том, что для оформления таких эдементов удобно выделить отдельный класс.

В принципе, сейчас это не обязательно. Просто ты начал их стилизовать, и я заметил.
А вообще про это еще будет

2021-06-09 01:02 UTC, wrgraff approved these changes

2021-06-09 01:02 UTC, merged