Размечает сетку главной страницы
htmlacademy-htmlcss/845199-nerds-31 pull request #6
Opened 2021-06-15 11:35 UTC by dopamine-s

2021-06-16 01:31 UTC, wrgraff requested changes
Итак, сделал [обзор отдельный с детальном рассмотрением некоторых моментов](https://youtu.be/sH6KyqiUYOQ).
Надеюсь, он часть вопросов закроет. Я что-то менее подробно указал в текстовом ревью и должно как раз хватить с видео.

Не особо пугайся количеству поправок, у тебя по сути ведь тут 2 задания: и крупные и мелкие сетки. Так что нормально все.

Ну и видео [про контакты](https://youtu.be/Ccmu3wrjY8o) (и в ролик ссылку на него встроил) лучше смотреть после обзора.

2021-06-17 00:14 UTC, dopamine-s commented on css/style.css
> +  padding: 0px;
Убрал. Это как в фильмах про "Чужих" каких-нибудь. На каждый шорох - залп на упреждение, на всякий случай. Так и я, с отъезжающими отступами, кругом распихал обнуление, где нужно и нет. 
Убрал.

2021-06-17 00:15 UTC, dopamine-s commented on css/outline.css
> +body * {
Оставил пока. Чуть позже уберу.

2021-06-17 00:15 UTC, dopamine-s commented on css/style.css
> +  margin: 0 auto;
Как лучше сделать, ограничить жестче, или убрать центровку?

2021-06-17 00:17 UTC, dopamine-s commented on css/style.css
> +  grid-template-rows: min-content 1fr;
Убрал

2021-06-17 00:25 UTC, dopamine-s commented on css/style.css
> +  margin-top: 49px;
Я понял. Убрал .main-header-wrapper. Прописал  для .main-header  padding-top: 49px 
 Работает.

2021-06-17 00:28 UTC, dopamine-s commented on css/style.css
> +  margin: 0 auto;
Убрал центровку

2021-06-17 00:56 UTC, dopamine-s commented on css/style.css
> +}
А. Вспомнил. У меня вылазили лишние отступы, я пытался с ними бороться. Все другие способы почему-то дают нижний отступ под картинкой. 
Нашел интересный вариант:
  .main-header-logo {
  display: contents;
}

2021-06-17 01:10 UTC, dopamine-s commented on css/style.css
> +}
.main-header-logo img {
  display: block;
}
Сделал так

2021-06-21 20:25 UTC, wrgraff requested changes
2 важных момента на доработку

2021-06-21 20:25 UTC, wrgraff commented on css/style.css
> +  height: 184px;
Смотри, о чем речь шла. Рисую для наглядности полоски сверху и снизу (очень похожие будут на макете):
![изображение](https://user-images.githubusercontent.com/37917037/122819964-c20d6900-d2e3-11eb-8bf8-f673e875dc74.png)

Добавляю второй ряд:
![изображение](https://user-images.githubusercontent.com/37917037/122820060-dcdfdd80-d2e3-11eb-9138-9ccb1e2c56c5.png)

Отступ между логотипами — больше, чем отступ от логотипа, до рамки. Это — неправильно, отступ между внутренними элементами должен быть меньше, чем от них до внешних.
Зачем это верстальщику знать? Ну, чтобы делать красивое переполнение и закладывать в него правильную логику. Дизайнеры не будут такие нюансы продумывать.

А как должно быть? Примерно так:
![изображение](https://user-images.githubusercontent.com/37917037/122821965-25989600-d2e6-11eb-9850-37f295611901.png)

Я уменьшил высоту и добавил отступы самому списку

2021-06-21 20:25 UTC, wrgraff commented on css/style.css
>    margin-left: 140px;
Не довел до ума контакты.
С отступом от левого края не то. Должна по контенту центрироваться плашка, а сейчас на широком экране уже не то:
![изображение](https://user-images.githubusercontent.com/37917037/122822867-53caa580-d2e7-11eb-8ce4-25326a448722.png)

При чем в инструкции у меня решено это

2021-06-24 09:40 UTC, wrgraff approved these changes

2021-06-24 09:40 UTC, merged