Создает разметку второй страницы
htmlacademy-htmlcss/845199-nerds-31 pull request #7
Opened 2021-06-26 10:10 UTC by dopamine-s

2021-06-27 04:28 UTC, wrgraff requested changes

2021-06-27 04:28 UTC, wrgraff commented on catalog.html
> +                    <input type="text" name="price-range-end-input" id="price-range-end-input" placeholder="15 000"/>
Какой-то тут бардак с отступами =)

2021-06-27 04:28 UTC, wrgraff commented on catalog.html
> +    <header class="header catalog-header">
Вообще, хэдеру не нужен специальный класс для отображения страницы каталога.
Они ведь не отличаются друг от друга ничем.
Ну и не ставить же нам на каждой странице свой класс. А что на счет страниц, которые пользователь сам захочет создать? Он там точно не сможет внятный класс придумать )

2021-06-27 04:28 UTC, wrgraff commented on catalog.html
> +    <header class="header catalog-header">
Вообще, хэдеру не нужен специальный класс для отображения страницы каталога.
Они ведь не отличаются друг от друга ничем.
Ну и не ставить же нам на каждой странице свой класс. А что на счет страниц, которые пользователь сам захочет создать? Он там точно не сможет внятный класс придумать )

2021-06-27 04:28 UTC, wrgraff commented on catalog.html
> +        <h1 class="title catalog-title">Магазин готовых шаблонов</h1>
Про H1 аналогично хэдеру: он не будет как-то отличаться между страницами

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +}
Лучше хэдеру задать один отступ и задать разные отступы от верхней части элементам, которые идут за хэдером

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +}
`.title` и `.catalog-title` это же один и тот же элемент

2021-06-27 04:28 UTC, wrgraff commented on catalog.html
> +                    <a class="visually-hidden" href="#">по убыванию</a>
Если вешать класс `visually-hidden`, то получается ссылка будет в доступности отображаться, но ее не будет видно.
А как нам кликнуть на то, чего не видно и что не имеет никакого размера?

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  grid-template-columns: 360px 360px;
Тут определенная логика есть, но я бы не стал в угоду дизайну сетку изменять как-то серьезно. Типы сортировки вроде как стоят в правой половине, но мне как-то кажется, что если добавится еще один, он мог бы влезть в строку и это было бы гармоничнее =)

Ну и обертка дополнительная тут не нужна, можно без нее эту сетку реализовать

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  grid-template-columns: 360px 360px;
Ну и даже при таком подходе лучше для создания двух равных колонок использовать `fr`, а не фиксированный размер в пикселях

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  justify-content: space-between;
Когда вот таким способом выравниваешь элементы, упускаешь из виду, что между ними еще отступы нужны. Текст может измениться, и это не должно привести к "слипанию"

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  grid-template-columns: 4fr 4fr;
Это равнозначно записи `grid-template-columns: 1fr 1fr;` =)

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  grid-row-gap: 70px;
Свойство `grid-gap` и его производные уже считаются устаревшими (вот так, только гриды появились, и...)
Это из-за того, что его сделали универсальным и будут использовать не только в гридах.
```suggestion
  column-gap: 40px;
  margin-bottom: 55px;
  row-gap: 70px;
```

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  width: 358px;
Там 360 ширина. Карточка сама тоже не 358, у нее только картинка такая, а сама карточка 360, так как у нее рамка есть.
<img width="302" alt="изображение" src="https://user-images.githubusercontent.com/37917037/123532720-5c244580-d718-11eb-8fd4-25af4644b047.png">

А вообще правильнее поставить 100%, так у тебя плашка всегда будет на ширину карточки, даже если карточка изменится по ширине.

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  width: 358px;
Там 360 ширина. Карточка сама тоже не 358, у нее только картинка такая, а сама карточка 360, так как у нее рамка есть.
<img width="302" alt="изображение" src="https://user-images.githubusercontent.com/37917037/123532720-5c244580-d718-11eb-8fd4-25af4644b047.png">

А вообще правильнее поставить 100%, так у тебя плашка всегда будет на ширину карточки, даже если карточка изменится по ширине.

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  flex-direction: column-reverse;
Вообще, без флекса вроде как вполне можно обойтись.
И тем более без колонки в обратном порядке. У тебя с ней вообще странная какая-то ситуация, ты сперва `order`'ом переставляешь параграф и кнопку вверх, а потом заставляешь всю колонку идти наоборот xD

2021-06-27 04:28 UTC, wrgraff commented on css/style.css
> +  width: 200px;
На всякий используй `min-width`

2021-06-27 17:59 UTC, dopamine-s commented on css/style.css
> +  width: 200px;
использовал

2021-06-27 18:32 UTC, dopamine-s commented on catalog.html
> +                    <input type="text" name="price-range-end-input" id="price-range-end-input" placeholder="15 000"/>
Совсем немного) Поправил

2021-06-27 18:32 UTC, dopamine-s commented on catalog.html
> +    <header class="header catalog-header">
Ок, понял. Отрегулирую верхними отступами следующих секций.

2021-06-27 18:32 UTC, dopamine-s commented on catalog.html
> +    <header class="header catalog-header">
Ок, понял. Отрегулирую верхними отступами следующих секций.

2021-06-27 18:32 UTC, dopamine-s commented on catalog.html
> +        <h1 class="title catalog-title">Магазин готовых шаблонов</h1>
Понял

2021-06-27 18:33 UTC, dopamine-s commented on css/style.css
> +}
Так и сделал

2021-06-27 18:34 UTC, dopamine-s commented on css/style.css
> +  grid-row-gap: 70px;
Изменил

2021-06-27 18:39 UTC, dopamine-s commented on css/style.css
> +  width: 358px;
Сделал

2021-06-27 18:40 UTC, dopamine-s commented on css/style.css
> +  width: 358px;
Сделал

2021-06-27 18:40 UTC, dopamine-s commented on css/style.css
> +  flex-direction: column-reverse;
Ну. Хотел реализовать защиту от переполнения сдвигом вверх

2021-06-28 08:48 UTC, wrgraff commented on catalog.html
> +                    <input type="text" name="price-range-end-input" id="price-range-end-input" placeholder="15 000"/>
Там прикол в том, что инпут не вложен в лейбл, поэтому не должен быть сдвинут по идее

2021-06-28 08:49 UTC, wrgraff commented on catalog.html
> +                    <a class="visually-hidden" href="#">по убыванию</a>
А тут не поправил.
Сделай внутри ссылки скрытый текст в спанчике

2021-06-28 08:51 UTC, wrgraff commented on css/style.css
> +  justify-content: space-between;
Тут тоже не поменял ничего.
Просто добавь margin к пунктам. Не обязательно даже чтобы они именно им отталкивались, главное чтобы он был и в случае чего подстраховал от слипания пунктов

2021-06-28 08:52 UTC, wrgraff commented on css/style.css
> +  grid-row-gap: 70px;
Ну это правильно, надо искать повторяющиеся ошибки: я же не буду в каждом прям месте писать )
Это и мне неудобно, и тебе непонятно зачем ревью, засоренное лишними комментами

2021-06-28 08:54 UTC, wrgraff commented on css/style.css
> +  flex-direction: column-reverse;
Мягко говоря )
Это бывает, особенно если заработался. Иногда так посмотришь свежим взглядом (на следующий день, например) на свою работу и такой: "какого лешего я такое понаписал, тут же одним параметром все решается..."

2021-06-28 08:55 UTC, wrgraff reviewed
Нуууу, ты как-то поправил все, что поправлял.
Там есть пара не исправленных комментов, которые как важные отмечены.

2021-06-28 09:44 UTC, dopamine-s commented on catalog.html
> +                    <input type="text" name="price-range-end-input" id="price-range-end-input" placeholder="15 000"/>
Понял

2021-06-28 09:54 UTC, dopamine-s commented on catalog.html
> +                    <a class="visually-hidden" href="#">по убыванию</a>
Пропустил этот комментарий. Исправил

2021-06-28 09:59 UTC, dopamine-s commented on css/style.css
> +  grid-template-columns: 360px 360px;
Оставил пока как есть. fr использовал

2021-06-28 10:25 UTC, dopamine-s commented on css/style.css
> +  justify-content: space-between;
Пропустил этот комментарий. 
Изменил.

2021-06-29 21:32 UTC, wrgraff approved these changes

2021-06-29 21:32 UTC, merged