Проект. Подготовка к защите
htmlacademy-htmlcss/845199-nerds-31 pull request #8
Opened 2021-07-05 20:48 UTC by dopamine-s

2021-07-05 23:09 UTC, wrgraff requested changes

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +  opacity: 0.4;
[DRY](https://ru.wikipedia.org/wiki/Don%E2%80%99t_repeat_yourself) — один из важнейших принципов в разработке.

Например, здесь (и выше, и ниже) куча свойств и параметров, которые можно было бы не повторять, а написать только раз.

Имеет смысл, например, разграничить и не смешивать разные типы контролов (радио и чекбоксы), но точно не нужно для псевдоэлемента отмеченного инпута заново писать позишн, контент, прозрачность...

А кое-что разное можно и к общему знаменателю привести.
_( Вообще, можно только картинку в итоге переписать )_

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +  margin-bottom: 18px;
В данном случае я бы рекомендовал на расхождение забить.
лучше уж пусть чуть выбивается, чем элементы скачут непойми зачем. Это косяк макета, который тоже не надо переносить в верстку

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +}
Очень много повторений

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +  height: 10px;
Хотелось бы ссылку, в которую попасть все-таки проще.
Сделай ее покрупнее

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +  width: 360px;
Зачем задавать конкретную ширину, если можно задать 100%?

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +    -23px 0 0 -0 var(--basic-white-100),
Минус ноль?

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +}
Ссылка не совпадает по размеру с тем, как она видится:
![изображение](https://user-images.githubusercontent.com/37917037/124523249-ff531a00-ddfe-11eb-837e-a6b96af6e800.png)

Это ссылка должна быть круглой и краснеть при наведении. А не `<li>`

2021-07-05 23:09 UTC, wrgraff commented on css/style.css
> +.social-ling:focus {
ling?

2021-07-06 16:51 UTC, dopamine-s commented on catalog.html
> +                  <input class="radio-filter-input visually-hidden" type="radio" name="grid-type" value="adaptive" id="grid-type-adaptive" checked/>
Принял к сведению. Оставлю на потом, доработаю по наличию времени.

2021-07-06 16:51 UTC, dopamine-s commented on catalog.html
> +         <ul class="social-links">
Исправил

2021-07-06 16:52 UTC, dopamine-s commented on catalog.html
> +            </a>
Поправил, согласен.

2021-07-06 16:54 UTC, dopamine-s commented on catalog.html
> +              <img src="img/fb-icon.svg" width="12" height="22" alt="Вконтакте"/>
Просто торопился, глянул в учебный проект, там картинки в разметке, сделал так же. Оставлю на потом, если будет время - поменяю.

2021-07-06 16:54 UTC, dopamine-s commented on catalog.html
> +      <button class="modal-close" type="button"><span class="visually-hidden">закрыть</span></button>
Хорошо, понял. Исправил

2021-07-06 17:01 UTC, dopamine-s commented on css/style.css
> + --basic-black-transparent-10: rgba(0, 0, 0, 0.0001);
Исправил. Убрал из базовых цветов. Использовал transparent в css.

2021-07-06 17:05 UTC, dopamine-s commented on css/style.css
> + --basic-black-transparent-150: rgba(0,0,0,0.1);
Пробелы поправил. Цвета оставил, потому что разница все-таки больше погрешности. При необходимости поменяю, но ведь это могут отметить при проверке, как неточность? 
Оставлю пока как есть, исправлю только синтаксис.

2021-07-06 19:28 UTC, dopamine-s commented on css/style.css
> +  background-color: var(--basic-red-500);
right: 0;   Еще вот это. 

Сделал

2021-07-06 19:58 UTC, dopamine-s commented on css/style.css
> +  left: 536px;
Даже не подумал, что тут дело в выравнивании по центру. Считал, что нужно отталкиваться от положения кнопки и уходить вправо. 
Переделал.

2021-07-06 20:00 UTC, dopamine-s commented on css/style.css
> +  border: solid 2px var(--basic-gray-375);
Поправил

2021-07-06 20:02 UTC, dopamine-s commented on css/style.css
> +  border: 1px solid var(--basic-gray-100);;
Для надежности. Бронебойная верстка, с запасом. 
Убрал.

2021-07-06 20:04 UTC, dopamine-s commented on css/style.css
> +  width: 260px;
Убрал

2021-07-06 20:07 UTC, dopamine-s commented on css/style.css
> +  top: -3px;
Не спорю. Возможно, это правильней. Но по макету-то именно так? И проверка будет это учитывать. Ведь будет кто-то еще проверять. Логичней придерживаться макета, насколько возможно. 
Пока оставлю так. Прочитал инфу по ссылке. Звучит вполне логично. Но пока оставлю так.

2021-07-06 20:17 UTC, dopamine-s commented on catalog.html
> +      <button class="modal-close" type="button"><span class="visually-hidden">закрыть</span></button>
Понял. Прошелся по тексту

2021-07-06 20:18 UTC, dopamine-s commented on css/style.css
> +  width: 77%;
Поправил

2021-07-06 20:25 UTC, dopamine-s commented on css/style.css
> +  opacity: 0.4;
И ширину, если придерживаться того, чтобы у нас галочка  checked все-таки выходила за рамку.

2021-07-06 20:27 UTC, dopamine-s commented on css/style.css
> +  margin-bottom: 18px;
Вообще я хотел так и сделать. Но перфекционизм заставил меня это повторить. Хотя это глупо. 
Переделал, конечно.

2021-07-06 20:35 UTC, dopamine-s commented on css/style.css
> +}
Пока оставлю. Если дать дополнительный общий класс, это не сократит особо код

2021-07-06 21:04 UTC, dopamine-s commented on css/style.css
> +  height: 10px;
Сделал

2021-07-06 21:05 UTC, dopamine-s commented on css/style.css
> +  width: 360px;
ОК, Босс. Сделал.

2021-07-06 21:06 UTC, dopamine-s commented on css/style.css
> +    -23px 0 0 -0 var(--basic-white-100),
Есть же НеЕвклидовая геометрия. Это неевклидовая Верстка)
Поправил.

2021-07-06 21:14 UTC, dopamine-s commented on css/style.css
> +.social-ling:focus {
Поправил

2021-07-07 01:20 UTC, dopamine-s commented on css/style.css
> +}
Сделал

2021-07-07 18:31 UTC, wrgraff commented on css/style.css
> + --basic-black-transparent-150: rgba(0,0,0,0.1);
Разница нулевая. Поизучай как rgb вообще работает.
Там добавлен поворот на 1/255 двух каналов из 3.

Вот, найди разницу, что с прозрачностью, что без:
![изображение](https://user-images.githubusercontent.com/37917037/124810899-883a9480-df6a-11eb-9fec-b459455f4b99.png)

А вот сдвиг на 50 единиц:
![изображение](https://user-images.githubusercontent.com/37917037/124811013-ad2f0780-df6a-11eb-9bca-d1488678bfed.png)
Вот он заметный (и то не очень).

2021-07-07 18:34 UTC, wrgraff commented on css/style.css
> +  top: -3px;
А при чем тут "по макету"?
Нет, по макету не так. Макет нам не диктует как именно компануются отдельные "куски" интерфейса. Он про это ничего не знает и выглядеть визуально будет все одинаково. Только в одной из версий в чекбокс попасть проще

2021-07-07 18:56 UTC, wrgraff commented on css/style.css
> +  background-position: center;
Чего-то не то намудрил.

Размер надо бы задать самой ссылке.
Оберток много, при чем они скорее мешают.

И почему вы все делаете псевдоэлементы абсолютом...
Это же не так уж и удобно. Особенно если задача вроде текущей.

Вот намного же меньше кода и проще, если [сделать так](https://www.dropbox.com/s/o8rr2h48br4jden/%25D0%2597%25D0%25B0%25D0%25BF%25D0%25B8%25D1%2581%25D1%258C%2520%25D1%258D%25D0%25BA%25D1%2580%25D0%25B0%25D0%25BD%25D0%25B0%25202021-07-07%2520%25D0%25B2%252021.47.28.mov?dl=0)

2021-07-07 18:56 UTC, wrgraff commented on css/style.css
> +  opacity: 0.4;
Я про галочку в курсе, то даже и так можно только картинку сменить

2021-07-07 18:58 UTC, wrgraff requested changes
Ну почти хорошо

2021-07-07 19:52 UTC, dopamine-s commented on css/style.css
> + --basic-black-transparent-150: rgba(0,0,0,0.1);
Ок, убедил. Переделал.

2021-07-07 20:48 UTC, dopamine-s commented on css/style.css
> +  background-position: center;
Переделал

2021-07-08 10:38 UTC, wrgraff approved these changes

2021-07-08 10:38 UTC, merged